"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path    
from datetime import timedelta
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        # Only for development
        SECRET_KEY = 'dev-only-secret-key-change-in-production'
    else:
        raise ValueError("SECRET_KEY environment variable is required in production")

# ALLOWED_HOSTS configuration
allowed_hosts_env = os.environ.get('ALLOWED_HOSTS')
if DEBUG:
    # Development: Allow localhost and local IPs
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0'] if not allowed_hosts_env else allowed_hosts_env.split(',')
else:
    # Production: Must be explicitly set, no defaults
    if not allowed_hosts_env:
        # For Render, try to auto-detect the domain
        render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
        if render_external_hostname:
            ALLOWED_HOSTS = [render_external_hostname]
        else:
            raise ValueError("ALLOWED_HOSTS environment variable is required in production")
    else:
        ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',')]
    
    # Security validation for production
    if '*' in ALLOWED_HOSTS:
        raise ValueError("Wildcard '*' in ALLOWED_HOSTS is not allowed in production")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Local apps
    'authentication',  # Clean separation of auth logic
    'procurement',     # Core business logic
    
    # Third party apps
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',  # API Documentation
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    # Production database - all credentials must be provided via environment
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('DB_NAME'),
            'USER': os.environ.get('DB_USER'), 
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST': os.environ.get('DB_HOST', 'localhost'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
    # Validate required database credentials
    required_db_vars = ['DB_NAME', 'DB_USER', 'DB_PASSWORD']
    missing_vars = [var for var in required_db_vars if not os.environ.get(var)]
    if missing_vars:
        raise ValueError(f"Required database environment variables missing: {missing_vars}")
else:
    # Development database
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES' : (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        ),
    'DEFAULT_PERMISSION_CLASSES' : (
        'rest_framework.permissions.IsAuthenticated',
        ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME' : timedelta(hours=6),
    'REFRESH_TOKEN_LIFETIME' : timedelta(days=1),
}

# CORS settings
cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS')
if DEBUG:
    # Development: Allow local frontend origins
    default_cors_origins = [
        "http://localhost:3000",
        "http://127.0.0.1:3000", 
        "http://localhost:3001",
        "http://127.0.0.1:3001",
    ]
    CORS_ALLOWED_ORIGINS = default_cors_origins if not cors_origins_env else cors_origins_env.split(',')
    CORS_ALLOW_ALL_ORIGINS = True  # Allow all in development
else:
    # Production: Must specify allowed origins
    if cors_origins_env:
        CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',')]
    else:
        CORS_ALLOWED_ORIGINS = []  # No CORS in production unless explicitly set
    CORS_ALLOW_ALL_ORIGINS = False

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # SSL/TLS settings for Render
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True

# DRF Spectacular (OpenAPI/Swagger) Configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'IST Africa Procure-to-Pay API',
    'DESCRIPTION': '''
    A comprehensive procurement management system with AI-powered document processing.
    
    ## Features
    - **Multi-level Approval Workflow**: Level 1 and Level 2 approvers
    - **AI Document Processing**: Automatic proforma data extraction and PO generation  
    - **Receipt Validation**: AI-powered receipt verification against purchase orders
    - **File Management**: Upload and manage proforma invoices, POs, and receipts
    - **JWT Authentication**: Secure API access with role-based permissions
    
    ## Authentication
    This API uses JWT authentication. Include the token in the Authorization header:
    `Authorization: Bearer <your_jwt_token>`
    
    ## Workflow
    1. **Create Request**: Staff users create purchase requests with proforma uploads
    2. **AI Processing**: System extracts data from proforma invoices
    3. **Approval Process**: Level 1 then Level 2 approver review
    4. **PO Generation**: Automatic purchase order creation for approved requests
    5. **Receipt Upload**: Upload and validate receipts against purchase orders
    ''',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'IST Africa Technical Team',
        'email': 'tech@ist-africa.org',
    },
    'LICENSE': {
        'name': 'MIT License',
    },
    'TAGS': [
        {
            'name': 'Purchase Requests',
            'description': 'CRUD operations for purchase requests'
        },
        {
            'name': 'Approvals', 
            'description': 'Multi-level approval workflow endpoints'
        },
        {
            'name': 'AI Processing',
            'description': 'AI-powered document processing and validation'
        },
        {
            'name': 'Authentication',
            'description': 'JWT token authentication endpoints'
        }
    ],
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
}

# This should be inside the production security block - let me check where this belongs