# Generated by Django 5.2.8 on 2025-11-26 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequest',
            options={},
        ),
        migrations.RenameField(
            model_name='purchaserequest',
            old_name='proforma_file',
            new_name='proforma',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='status',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='department',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='justification',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='po_generated_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='urgency',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='requestitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='approval',
            name='approved',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order',
            field=models.FileField(blank=True, null=True, upload_to='purchase_orders/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_validation_data',
            field=models.JSONField(blank=True, help_text='Receipt validation results', null=True),
        ),
        migrations.AddField(
            model_name='requestitem',
            name='name',
            field=models.CharField(default='Item', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approval',
            name='level',
            field=models.IntegerField(choices=[(1, 'Level 1 Approver'), (2, 'Level 2 Approver')]),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='proforma_data',
            field=models.JSONField(blank=True, help_text='AI-extracted data from proforma', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_order_data',
            field=models.JSONField(blank=True, help_text='Generated PO data', null=True),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='requestitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='approval',
            constraint=models.CheckConstraint(condition=models.Q(('approved__in', [True, False])), name='valid_approval_status'),
        ),
    ]
