# Generated by Django 5.2.8 on 2025-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_alter_purchaserequest_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='po_generated_at',
            field=models.DateTimeField(blank=True, help_text='When PO was generated', null=True),
        ),
    ]
