# Generated by Django 5.2.8 on 2025-11-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='department',
            field=models.CharField(blank=True, help_text='Requesting department', max_length=100),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='justification',
            field=models.TextField(blank=True, help_text='Business justification for purchase'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='po_generated_at',
            field=models.DateTimeField(blank=True, help_text='When PO was generated', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_data',
            field=models.JSONField(blank=True, help_text='AI-extracted data from proforma', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='purchase_order_data',
            field=models.JSONField(blank=True, help_text='Generated PO data', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_validation_data',
            field=models.JSONField(blank=True, help_text='Receipt validation results', null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='urgency',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20),
        ),
    ]
